<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<h1>Навигация</h1>
        <ul>
            <li><a href ="/">Главная</a></li>            
            <li><a href ="/about">О нас</a></li>
            <li><a href ="/contacts">Контакты</a></li>
            <li><a href ="/help">Помощь</a></li>
            <li><a href ="/info">phpinfo</a></li>
            <li><a href ="/error">Ошибка</a></li>
        </ul>
<?php
include_once VIEWS . $content_view;
?>
</body>
</html>